### ISSUE TITLE
Are or will be these colormaps merged back to matplotlib?

### ISSUE THREAD

**Issue by KOLANICH** [bokeh/colorcet#13]

**Comment by bryevdv** [comment]
It's entirely up to the Matplotlib developers when or if or how these would be included in MPL. However  given that several projects use these colormaps, no just MPL, in my own opinion it would be much more sensible for MPL to add colorcet as a runtime dependency, rather than duplicatively vending literal code.

**Comment by KOLANICH** [comment]
Every 3rd-party dependency is a risk. It may make more sense to put the code into mpl and add a dummy package importing the stuff from mpl (and displaying a warning) just for compatibility.

**Comment by bryevdv** [comment]
I can state fairly confidently that the owners of this package wish it to remain separate.  MPL devs could take it upon themselves to vendor the code if they choose. I note that none of the people in this project are MPL devs, so this is not really a useful place to take that question up.

**Comment by KOLANICH** [comment]
>I can state fairly confidently that the owners of this package wish it to remain separate. 

That's what I wanted to know, thank you.
